/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class july_appn_July */

#ifndef _Included_july_appn_July
#define _Included_july_appn_July
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     july_appn_July
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_july_appn_July_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
